"""Bug fix in binary representation of days

Revision ID: 243e14661a08
Revises: 5893a8292af2
Create Date: 2020-07-10 21:00:15.996836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '243e14661a08'
down_revision = '5893a8292af2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day_binary_representation', sa.Column('id', sa.Integer(), nullable=False, default=-1, server_default=-1))
    op.alter_column('day_binary_representation', 'weekday',
               existing_type=sa.INTEGER(),
               nullable=True,
               default=-1
               )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('day_binary_representation', 'weekday',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('day_binary_representation', 'id')
    # ### end Alembic commands ###
