"""Binary representations of days

Revision ID: aac8005577ad
Revises: 91a69ee2356e
Create Date: 2020-07-07 13:03:12.894326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aac8005577ad'
down_revision = '91a69ee2356e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_binary_representation',
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('value', sa.LargeBinary(length=128), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.PrimaryKeyConstraint('weekday')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('day_binary_representation')
    # ### end Alembic commands ###
