"""Indexed google_id

Revision ID: c7e8c8998938
Revises: f47bb1d6f9ed
Create Date: 2020-07-24 22:53:03.800159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7e8c8998938'
down_revision = 'f47bb1d6f9ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_public_id'), 'user', ['public_id'], unique=True)
    op.drop_index('ix_user_google_id', table_name='user')
    op.create_index(op.f('ix_user_google_id'), 'user', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_google_id'), table_name='user')
    op.create_index('ix_user_google_id', 'user', ['google_id'], unique=False)
    op.drop_index(op.f('ix_user_public_id'), table_name='user')
    # ### end Alembic commands ###
