"""User, Schedule, Day and DayBinaryRepresentation

Revision ID: e79874d27df0
Revises: 
Create Date: 2020-07-10 23:37:13.408481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e79874d27df0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_id', sa.String(length=32), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_google_id'), 'user', ['google_id'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.SmallInteger(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_week_number'), 'schedule', ['week_number'], unique=False)
    op.create_table('class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course', sa.String(length=16), nullable=True),
    sa.Column('weekday', sa.SmallInteger(), nullable=True),
    sa.Column('begins', sa.Integer(), nullable=True),
    sa.Column('ends', sa.Integer(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_begins'), 'class', ['begins'], unique=False)
    op.create_index(op.f('ix_class_ends'), 'class', ['ends'], unique=False)
    op.create_index(op.f('ix_class_weekday'), 'class', ['weekday'], unique=False)
    op.create_table('day_binary_representation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=True),
    sa.Column('value', sa.LargeBinary(length=128), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('day_binary_representation')
    op.drop_index(op.f('ix_class_weekday'), table_name='class')
    op.drop_index(op.f('ix_class_ends'), table_name='class')
    op.drop_index(op.f('ix_class_begins'), table_name='class')
    op.drop_table('class')
    op.drop_index(op.f('ix_schedule_week_number'), table_name='schedule')
    op.drop_table('schedule')
    op.drop_table('followers')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_google_id'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
