"""follow table update

Revision ID: f47bb1d6f9ed
Revises: 91a8fe09e336
Create Date: 2020-07-22 17:31:12.141660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f47bb1d6f9ed'
down_revision = '91a8fe09e336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('priority_level', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.drop_table('followers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.INTEGER(), nullable=False),
    sa.Column('followed_id', sa.INTEGER(), nullable=False),
    sa.Column('priority_level', sa.SMALLINT(), nullable=True),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.drop_table('follow')
    # ### end Alembic commands ###
